parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'

env:
  es2017: true
  browser: true

extends: 'htmlacademy/vanilla'
parser: '@babel/eslint-parser'

globals:
  ymaps: readonly
  app: readonly
  global: readonly
  process: readonly

rules:
  indent: ["error", "tab"]
